import { db } from '../db/index.ts';
import { notifications, notificationDeliveries, notificationPreferences, employees, users } from '../db/schema.ts';
import { eq, and } from 'drizzle-orm';
import { NotificationService } from '../notifications/notification.service.ts';
import { NotificationTemplateEngine } from '../notifications/notification.templates.ts';
import { NotificationPermissions } from '../notifications/notification.permissions.ts';
import { EmailProvider, WhatsAppProvider, SMSProvider } from '../notifications/notification.providers.ts';

function assert(condition: boolean, message: string) {
  if (!condition) {
    throw new Error(`Assertion Failed: ${message}`);
  }
  console.log(`  PASS: ${message}`);
}

export async function runNotificationTests() {
  console.log('====================================================');
  console.log('[11/11] STARTING ENTERPRISE NOTIFICATION MODULE TEST SUITE');
  console.log('====================================================');

  let passed = 0;
  let failed = 0;

  const runTest = async (name: string, fn: () => Promise<void>) => {
    try {
      await fn();
      passed++;
    } catch (err: any) {
      console.error(`  FAIL: ${name} ->`, err.message);
      failed++;
    }
  };

  // Find a test employee & user
  const [testEmp] = await db.select().from(employees).limit(1);
  const [testUser] = await db.select().from(users).where(eq(users.username, 'admin')).limit(1);
  const [empUser] = await db.select().from(users).where(eq(users.username, 'aminata.turay')).limit(1);

  // 1. Template Engine & Safe Variable Substitution
  await runTest('Template Engine safely substitutes approved whitelist variables', async () => {
    const rendered = NotificationTemplateEngine.render(
      'Good morning, {{employee_name}}. Your attendance was recorded at {{check_in_time}}.',
      {
        employee_name: 'Aminata Turay',
        check_in_time: '08:05:00',
      }
    );
    assert(
      rendered === 'Good morning, Aminata Turay. Your attendance was recorded at 08:05:00.',
      'Template Engine substituted approved variables correctly'
    );
  });

  await runTest('Template Engine neutralizes unapproved / injected variables', async () => {
    const rendered = NotificationTemplateEngine.render(
      'Notice: {{employee_name}}, password is {{password_hash}}.',
      {
        employee_name: 'Aminata Turay',
        password_hash: 'secret123',
      }
    );
    assert(
      rendered === 'Notice: Aminata Turay, password is .',
      'Unapproved variable {{password_hash}} was strictly stripped'
    );
  });

  await runTest('Template Engine sanitizes malicious HTML and script tags (XSS protection)', async () => {
    const maliciousInput = '<script>alert("XSS")</script>';
    const rendered = NotificationTemplateEngine.render('Message: {{message}}', {
      message: maliciousInput,
    });
    assert(
      !rendered.includes('<script>') && rendered.includes('&lt;script&gt;'),
      'HTML/Script tags properly sanitized to HTML entities'
    );
  });

  // 2. Action URL Validation (Open Redirect Protection)
  await runTest('Action URL validator allows safe internal relative routes', async () => {
    const safeUrl = NotificationService.validateActionUrl('/attendance');
    assert(safeUrl === '/attendance', 'Relative path /attendance is permitted');
  });

  await runTest('Action URL validator rejects javascript: and external open redirects', async () => {
    const dangerousUrl1 = NotificationService.validateActionUrl('javascript:alert(1)');
    const dangerousUrl2 = NotificationService.validateActionUrl('http://malicious-phishing.com/login');
    assert(dangerousUrl1 === null, 'javascript: URI scheme strictly blocked');
    assert(dangerousUrl2 === null, 'External phishing redirect strictly blocked');
  });

  // 3. Notification Dispatch & Idempotency
  await runTest('NotificationService creates notification record with multi-channel deliveries', async () => {
    const notif = await NotificationService.dispatch({
      employeeId: testEmp.id,
      title: 'QA Automated Test Alert',
      message: 'This is a test notification generated by the QA test suite.',
      category: 'Attendance',
      type: 'ATTENDANCE',
      priority: 'normal',
      channel: ['in_app', 'email'],
    });

    assert(Boolean(notif && notif.id), 'Notification record created in PostgreSQL');

    // Verify delivery entries
    const deliveries = await db
      .select()
      .from(notificationDeliveries)
      .where(eq(notificationDeliveries.notificationId, notif.id));

    assert(deliveries.length >= 1, 'Delivery tracking records created in notification_deliveries');
  });

  await runTest('Idempotency prevents duplicate notifications for identical events', async () => {
    const idempotencyKey = `qa-idemp-${Date.now()}`;

    const notif1 = await NotificationService.dispatch({
      employeeId: testEmp.id,
      title: 'Check-In Confirmation',
      message: 'Your attendance has been recorded.',
      category: 'Attendance',
      type: 'ATTENDANCE',
      idempotencyKey,
    });

    const notif2 = await NotificationService.dispatch({
      employeeId: testEmp.id,
      title: 'Check-In Confirmation',
      message: 'Your attendance has been recorded.',
      category: 'Attendance',
      type: 'ATTENDANCE',
      idempotencyKey,
    });

    assert(notif1.id === notif2.id, 'Idempotency key prevented duplicate insert and returned original record');
  });

  // 4. Mark As Read & Unread Count
  await runTest('Mark as read updates status and decrements unread count', async () => {
    const notif = await NotificationService.dispatch({
      userId: testUser.id,
      title: 'Unread Counter Test',
      message: 'Testing unread counter update.',
      category: 'System',
    });

    const updated = await NotificationService.markAsRead(notif.id, {
      id: testUser.id,
      username: testUser.username,
      roleName: 'Administrator',
    });

    assert(updated.isRead === true && updated.readAt !== null, 'Notification marked as read with timestamp');
  });

  // 5. RBAC & Access Control Checks
  await runTest('Administrator has permission to broadcast to all employees', async () => {
    const canBroadcast = NotificationPermissions.canSendMassBroadcast({
      id: testUser.id,
      username: testUser.username,
      roleName: 'Administrator',
    });
    assert(canBroadcast === true, 'Administrator is permitted to broadcast');
  });

  await runTest('Standard Employee is strictly DENIED from sending mass broadcast', async () => {
    const canBroadcast = NotificationPermissions.canSendMassBroadcast({
      id: empUser.id,
      username: empUser.username,
      roleName: 'Employee',
      employeeId: empUser.employeeId,
    });
    assert(canBroadcast === false, 'Employee is strictly denied from mass broadcast');
  });

  await runTest('Employee attempting unauthorized mass broadcast throws error', async () => {
    let errorThrown = false;
    try {
      await NotificationService.broadcast(
        {
          recipientGroup: 'all',
          title: 'Unauthorized Employee Announcement',
          message: 'This should fail.',
        },
        {
          id: empUser.id,
          username: empUser.username,
          roleName: 'Employee',
          employeeId: empUser.employeeId,
        }
      );
    } catch {
      errorThrown = true;
    }
    assert(errorThrown === true, 'Unauthorized employee broadcast operation blocked with exception');
  });

  await runTest('Employee cannot modify notification preferences belonging to another employee (IDOR)', async () => {
    const canManageForeign = NotificationPermissions.canManagePreferences(
      {
        id: empUser.id,
        username: empUser.username,
        roleName: 'Employee',
        employeeId: empUser.employeeId,
      },
      9999 // Different employee ID
    );
    assert(canManageForeign === false, 'Employee denied from editing foreign preferences');
  });

  // 6. Provider Validations
  await runTest('EmailProvider validates recipient email address format', async () => {
    const invalidEmailRes = await EmailProvider.send({
      id: 1,
      recipientName: 'Test User',
      toEmail: 'not-a-valid-email',
      title: 'Email Test',
      message: 'Test message',
      category: 'System',
      priority: 'normal',
    });
    assert(invalidEmailRes.success === false, 'EmailProvider properly rejected invalid email format');

    const validEmailRes = await EmailProvider.send({
      id: 1,
      recipientName: 'Test User',
      toEmail: 'test.user@apexenterprise.com',
      title: 'Email Test',
      message: 'Test message',
      category: 'System',
      priority: 'normal',
    });
    assert(validEmailRes.success === true, 'EmailProvider accepted valid email address format');
  });

  await runTest('WhatsApp and SMS provider adapters validate phone number format', async () => {
    const invalidWa = await WhatsAppProvider.send({
      id: 1,
      recipientName: 'Test User',
      toPhone: '123',
      title: 'WA Test',
      message: 'Hello',
      category: 'System',
      priority: 'normal',
    });
    assert(invalidWa.success === false, 'WhatsApp adapter rejected truncated phone number');

    const invalidSms = await SMSProvider.send({
      id: 1,
      recipientName: 'Test User',
      toPhone: '',
      title: 'SMS Test',
      message: 'Hello',
      category: 'System',
      priority: 'normal',
    });
    assert(invalidSms.success === false, 'SMS adapter rejected empty phone number');
  });

  // 7. Non-Blocking Transaction Safety (Section 39 & 63)
  await runTest('Notification delivery failure does not roll back parent business transactions', async () => {
    let transactionSucceeded = false;
    try {
      // Simulate business operation: e.g. Attendance or Payroll
      // If notification dispatch throws or provider fails, transaction must remain safe
      try {
        await NotificationService.dispatch({
          employeeId: testEmp.id,
          title: 'Transaction Safety Check',
          message: 'Verifying notification errors do not abort core operations.',
          category: 'Payroll',
          type: 'PAYROLL',
        });
      } catch (notifErr) {
        console.warn('Caught non-fatal notification error:', notifErr);
      }
      transactionSucceeded = true;
    } catch {
      transactionSucceeded = false;
    }

    assert(transactionSucceeded === true, 'Attendance/Payroll transaction completes successfully even if notification fails');
  });

  console.log(`--- Notification Test Results: ${passed} Passed, ${failed} Failed ---`);
  return { passed, failed };
}
