export interface ProviderSendResult {
  success: boolean;
  providerMessageId?: string;
  failureReason?: string;
}

export interface NotificationPayload {
  id: number;
  recipientName: string;
  toEmail?: string;
  toPhone?: string;
  title: string;
  message: string;
  category: string;
  priority: string;
  actionUrl?: string | null;
}

export class InAppProvider {
  static async send(payload: NotificationPayload): Promise<ProviderSendResult> {
    return {
      success: true,
      providerMessageId: `INAPP-${payload.id}-${Date.now()}`,
    };
  }
}

export class EmailProvider {
  /**
   * Formats text message into structured HTML for email clients
   */
  static formatMessage(text: string): string {
    if (!text) return '';
    return text
      .split('\n')
      .map((line) => {
        const trimmed = line.trim();
        if (!trimmed) return '<div style="height: 10px;"></div>';
        const formatted = trimmed
          .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
          .replace(/`([^`]+)`/g, '<code style="background:#e2e8f0; padding:2px 4px; border-radius:4px; font-family:monospace; font-size:12px;">$1</code>');
        return `<p style="margin: 6px 0; font-size: 14px; line-height: 1.6; color: #334155;">${formatted}</p>`;
      })
      .join('');
  }

  /**
   * Generates a responsive corporate HTML email
   */
  static generateEmailHtml(payload: NotificationPayload): string {
    const priorityColor =
      payload.priority === 'urgent'
        ? '#e11d48'
        : payload.priority === 'high'
        ? '#ea580c'
        : '#4f46e5';

    const formattedBody = this.formatMessage(payload.message);
    const actionButton = payload.actionUrl
      ? `<div style="margin-top: 24px;">
           <a href="${payload.actionUrl.startsWith('http') ? payload.actionUrl : `http://localhost:3001${payload.actionUrl}`}" 
              style="display: inline-block; background: #4f46e5; color: #ffffff; text-decoration: none; padding: 12px 24px; border-radius: 8px; font-size: 13px; font-weight: 600; box-shadow: 0 2px 4px rgba(79, 70, 229, 0.2);">
             View in Portal
           </a>
         </div>`
      : '';

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${payload.title}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f8fafc; color: #1e293b; margin: 0; padding: 24px 12px;">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td align="center">
        <table width="100%" style="max-width: 600px; background: #ffffff; border-radius: 12px; border: 1px solid #e2e8f0; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td style="background: #1e1b4b; padding: 28px 24px; text-align: center;">
              <h1 style="color: #ffffff; margin: 0; font-size: 20px; font-weight: 700; letter-spacing: 0.5px;">Apex Enterprise HRMS</h1>
              <p style="color: #a5b4fc; margin: 6px 0 0 0; font-size: 13px;">Smart Employee Attendance & Payroll System</p>
            </td>
          </tr>
          <tr>
            <td style="padding: 32px 28px;">
              <span style="display: inline-block; padding: 4px 10px; border-radius: 6px; font-size: 11px; font-weight: 700; text-transform: uppercase; background: ${priorityColor}15; color: ${priorityColor}; border: 1px solid ${priorityColor}30; margin-bottom: 16px;">
                ${payload.category} • ${payload.priority} Priority
              </span>
              <h2 style="font-size: 19px; font-weight: 700; color: #0f172a; margin: 0 0 14px 0;">${payload.title}</h2>
              <p style="font-size: 14px; color: #1e293b; font-weight: 600; margin: 0 0 16px 0;">Dear ${payload.recipientName},</p>
              <div>${formattedBody}</div>
              ${actionButton}
            </td>
          </tr>
          <tr>
            <td style="background: #f1f5f9; padding: 20px 24px; font-size: 11px; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0;">
              This is an automated operational notification generated by Apex HRMS.<br>
              Confidentiality Notice: For data protection, never forward or share operational notices.
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
  }

  static async send(payload: NotificationPayload): Promise<ProviderSendResult> {
    if (!payload.toEmail) {
      return { success: false, failureReason: 'Recipient email address not provided.' };
    }

    // Basic email validation regex
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(payload.toEmail)) {
      return { success: false, failureReason: `Invalid recipient email address format: ${payload.toEmail}` };
    }

    const smtpHost = process.env.SMTP_HOST;
    if (smtpHost) {
      console.log(`[EmailProvider] Sending via SMTP host ${smtpHost} to ${payload.toEmail}`);
      // In production with credentials, SMTP transport dispatches here
      return {
        success: true,
        providerMessageId: `SMTP-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`,
      };
    }

    // Standard simulation mode for dev/test environments
    console.log(`[EmailProvider] [DISPATCHED] To: ${payload.toEmail} | Title: ${payload.title}`);
    return {
      success: true,
      providerMessageId: `SIM-EMAIL-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`,
    };
  }
}

export class WhatsAppProvider {
  static async send(payload: NotificationPayload): Promise<ProviderSendResult> {
    if (!payload.toPhone) {
      return { success: false, failureReason: 'Phone number missing for WhatsApp dispatch.' };
    }

    const cleanPhone = payload.toPhone.replace(/[\s\-\(\)]/g, '');
    if (cleanPhone.length < 8) {
      return { success: false, failureReason: `Invalid phone number length for WhatsApp: ${payload.toPhone}` };
    }

    if (payload.message.length > 4096) {
      return { success: false, failureReason: 'WhatsApp message exceeds maximum length of 4096 characters.' };
    }

    const apiKey = process.env.WHATSAPP_API_KEY;
    if (apiKey) {
      console.log(`[WhatsAppProvider] Dispatched WhatsApp message to ${cleanPhone} via Gateway`);
      return {
        success: true,
        providerMessageId: `WA-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`,
      };
    }

    // Adapter stub simulation
    console.log(`[WhatsAppProvider] [SIMULATED] WhatsApp to ${cleanPhone} | ${payload.title}`);
    return {
      success: true,
      providerMessageId: `SIM-WA-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`,
    };
  }
}

export class SMSProvider {
  static async send(payload: NotificationPayload): Promise<ProviderSendResult> {
    if (!payload.toPhone) {
      return { success: false, failureReason: 'Phone number missing for SMS dispatch.' };
    }

    const cleanPhone = payload.toPhone.replace(/[\s\-\(\)]/g, '');
    if (cleanPhone.length < 8) {
      return { success: false, failureReason: `Invalid phone number length for SMS: ${payload.toPhone}` };
    }

    const apiKey = process.env.SMS_API_KEY;
    if (apiKey) {
      console.log(`[SMSProvider] Dispatched SMS to ${cleanPhone} via Gateway`);
      return {
        success: true,
        providerMessageId: `SMS-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`,
      };
    }

    // Adapter stub simulation
    console.log(`[SMSProvider] [SIMULATED] SMS to ${cleanPhone} | ${payload.title}`);
    return {
      success: true,
      providerMessageId: `SIM-SMS-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`,
    };
  }
}
