import React from 'react';
import { X, FileText, Download, Share2, Copy, Check, Printer, ShieldCheck } from 'lucide-react';
import { AIAssistantLogo } from './AIAssistantLogo.tsx';
import { AIMarkdownRenderer } from './AIMarkdownRenderer.tsx';
import { exportAiResponseToPdf, exportAiResponseToExcel, shareAiResponse } from '../../utils/aiExportUtils.ts';

interface AIFullViewModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  content: string;
  timestamp?: string;
  username?: string;
}

export const AIFullViewModal: React.FC<AIFullViewModalProps> = ({
  isOpen,
  onClose,
  title,
  content,
  timestamp,
  username = 'Authorized User',
}) => {
  const [copied, setCopied] = React.useState(false);
  const [exportNotice, setExportNotice] = React.useState<string | null>(null);

  if (!isOpen) return null;

  const showToast = (msg: string) => {
    setExportNotice(msg);
    setTimeout(() => setExportNotice(null), 3000);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      showToast('Full message copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      showToast('Failed to copy');
    }
  };

  const handlePdf = () => {
    const success = exportAiResponseToPdf(title, content, username);
    if (success) {
      showToast('Opening PDF print preview...');
    }
  };

  const handleExcel = () => {
    const success = exportAiResponseToExcel(title, content);
    if (success) {
      showToast('Downloaded Excel file (.xls)');
    }
  };

  const handleShare = async () => {
    const res = await shareAiResponse(title, content);
    if (res === 'copied') {
      showToast('Report copied to clipboard for sharing');
    } else if (res === 'shared') {
      showToast('Shared successfully');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-4xl max-h-[90vh] flex flex-col rounded-2xl border border-purple-500/30 bg-slate-900 shadow-2xl shadow-purple-950/50 overflow-hidden">
        {/* Modal Top Header Bar */}
        <div className="flex items-center justify-between border-b border-slate-800 bg-slate-950/90 px-5 py-4 shrink-0">
          <div className="flex items-center space-x-3">
            <AIAssistantLogo size="sm" withGlow={true} />
            <div>
              <h2 className="text-sm sm:text-base font-bold text-white flex items-center gap-2">
                <span>{title || 'Apex AI Intelligence Response'}</span>
                <span className="hidden sm:inline-flex rounded-full bg-purple-500/20 px-2.5 py-0.5 text-xs font-semibold text-purple-300 border border-purple-500/30">
                  Full View
                </span>
              </h2>
              <p className="text-xs text-slate-400">
                Generated by Apex AI Copilot • {timestamp || new Date().toLocaleString('en-GB')}
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white transition"
            title="Close Full View"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Action Controls Toolbar inside Modal */}
        <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800/80 bg-slate-900/60 px-5 py-2.5 text-xs">
          <div className="flex items-center space-x-2 text-slate-400">
            <ShieldCheck className="h-3.5 w-3.5 text-emerald-400" />
            <span>Audited & verified against Sierra Leone labor rules & PostgreSQL</span>
          </div>

          <div className="flex items-center space-x-2">
            <button
              type="button"
              onClick={handlePdf}
              className="inline-flex items-center space-x-1.5 rounded-lg bg-indigo-600/20 border border-indigo-500/30 px-3 py-1.5 text-indigo-200 hover:bg-indigo-600/30 hover:text-white transition active:scale-95"
            >
              <FileText className="h-3.5 w-3.5" />
              <span>Save as PDF</span>
            </button>

            <button
              type="button"
              onClick={handleExcel}
              className="inline-flex items-center space-x-1.5 rounded-lg bg-emerald-600/20 border border-emerald-500/30 px-3 py-1.5 text-emerald-200 hover:bg-emerald-600/30 hover:text-white transition active:scale-95"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Save as Excel</span>
            </button>

            <button
              type="button"
              onClick={handleShare}
              className="inline-flex items-center space-x-1.5 rounded-lg bg-slate-800 border border-slate-700 px-3 py-1.5 text-slate-300 hover:bg-slate-700 hover:text-white transition active:scale-95"
            >
              <Share2 className="h-3.5 w-3.5" />
              <span>Share</span>
            </button>

            <button
              type="button"
              onClick={handleCopy}
              className="inline-flex items-center space-x-1.5 rounded-lg bg-slate-800 border border-slate-700 px-3 py-1.5 text-slate-300 hover:bg-slate-700 hover:text-white transition active:scale-95"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>
          </div>
        </div>

        {/* Scrollable Content Body with Rich Markdown & Table Renderer */}
        <div className="flex-1 overflow-y-auto p-5 sm:p-7 space-y-4">
          <AIMarkdownRenderer content={content} />
        </div>

        {/* Notification Toast in Modal if action performed */}
        {exportNotice && (
          <div className="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full bg-slate-950/90 border border-purple-500/40 px-4 py-2 text-xs font-semibold text-purple-200 shadow-xl backdrop-blur-md animate-in slide-in-from-bottom-2">
            {exportNotice}
          </div>
        )}
      </div>
    </div>
  );
};
